version: '3.8'

volumes:
  sandbox_db:

services:
  sandbox_db:
    image: 'postgres:13.5-alpine3.15'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata/brandi_sandbox
      - POSTGRES_DB=brandi_sandbox
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - '5001:5432'
      - '5432:5432'
